title: "ICCC 320 – Data & Networked Interaction Fall 2026"
description: "Course materials for ICCC 320 at California Institute of the Arts"
url: "https://maxfishman.github.io"
baseurl: "/ICCC-320-Data-Networked-Interaction-Fall-2026"
theme: null
